board_type: chess_board
board_parameters:
  cols: 8
  rows: 6
  cell_size: 0.1
calibrator_type: opencv
calibration_parameters:
  radial_distortion_coefficients: 4
  pre_rejection_max_rms_error: 5.0
  post_rejection_max_rms_error: 3.0
data_collector:
  max_allowed_max_reprojection_error: 1.5
  max_allowed_rms_reprojection_error: 1.0
