/**:
  ros__parameters:
    time_window: 4.0
    gyro_estimation:
      only_use_straight: true
      only_use_moving: false
      only_use_constant_velocity: false
    velocity_estimation:
      only_use_straight: true
      only_use_moving: true
      only_use_constant_velocity: true
