name: sync-tier4-universe-to-humble
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Run sync-branches
        uses: autowarefoundation/autoware-github-actions/sync-branches@v1
        with:
          token: ${{ steps.generate-token.outputs.token }}
          base-branch: humble
          sync-target-repository: git@github.com:tier4/CalibrationTools.git
          sync-target-branch: tier4/universe
          sync-branch: sync-tier4-universe-to-humble
          pr-title: "chore: sync tier4/universe to humble"
          auto-merge-method: merge
